Rails/nicole_twitter1/config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'

  post 'unfollow' => 'epicenter#unfollow'

  get 'js_practice' => 'epicenter#js_practice'

  resources :tweets
  devise_for :users

end

Rails/nicole_twitter1/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :message, presence: true
  validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}

end

Rails/nicole_twitter1/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

serialize :following, Array
validates :username, presence: true
validates :username, uniqueness: true

has_many :tweets

end

Rails/nicole_twitter1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following) }

  end
end

Rails/nicole_twitter1/app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  def feed  
  @following_tweets = []

  @tweets = Tweet.all
  @users = User.all
  @follower_count = 0

  if user_signed_in?
	@tweets.each do |tweet|
  		current_user.following.each do |f|
  			if tweet.user_id == f
  				@following_tweets.push(tweet)
  			end
  		end
	end
 	@users.each do |user|
 	  if user.following.include?(current_user.id)
 	  	@following_count =+ 1
 	  end
 	end
 	else
 		redirect_to new_user_session_path
 	end
end

def show_user
	@user = User.find(params[:id])
end

def now_following
	@user = User.find(params[:follow_id])

	current_user.following.push(params[:follow_id].to_i)

	current_user.save
end

def unfollow
    @user = User.find(params[:unfollow_id])
    
    current_user.following.delete(params[:unfollow_id].to_i)
    
    current_user.save
  end
end

def js_practice
end

Rails/nicole_twitter1/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

Rails/nicole_twitter1/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/nicole_twitter1/app/helpers/epicenter_helper.rb
module EpicenterHelper
end

Rails/nicole_twitter1/app/helpers/tweets_helper.rb
module TweetsHelper
end

Rails/nicole_twitter1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NicoleTwitter</title>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
</head>
<body>

<% if user_signed_in? %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Tweets", tweets_path, class: "navbar-brand" %>
       <ul class= "nav navbar-nav navbar-left">
       </ul>
       <ul class= "nav navbar-nav navbar-right">
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
       </ul>
     </div>
  </div>
</nav>
<% else %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
  	<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tweets", tweets_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Sign Up", new_user_registration_path %></li>
    		<li><%= link_to "Forgot Password", edit_user_password_path %></li>
          </ul>
      </div>
    </div>
  </nav>
<% end %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>



    

Rails/nicole_twitter1/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :message, placeholder: "What are you thinking?" %>
  </div>
  <div class="field cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet!" %>
  </div>
<% end %>

Rails/nicole_twitter1/app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

Rails/nicole_twitter1/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<div class="row">
  <% @tweets.each do |tweet| %>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body"> 
          <%= tweet.message %>
          <%= link_to tweet.user.username, user_profile_path(id: tweet.user.id) %>
          <%= link_to 'Show', tweet %>
          <%= link_to 'Edit', edit_tweet_path(tweet) %>
          <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
<% end %>
      



<%= link_to 'New Tweet', new_tweet_path %>

Rails/nicole_twitter1/app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

Rails/nicole_twitter1/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, user_profile_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>